version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: terraform
    directories:
      - /terraform/shared
      - /terraform/environments/dev
      - /terraform/environments/prod
      - /terraform/modules/*
    schedule:
      interval: weekly
